- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Create Kubernetes Pod
      k8s:
        state: present
        src: /var/lib/jenkins/workspace/Purdue_IGP_2/pod.yaml 
    - name: Create Kubernetes Service
      k8s:
        state: present
        src: /var/lib/jenkins/workspace/Purdue_IGP_2/service.yaml
    - name: Create Kubernetes Deployment
      k8s:
        state: present
        src: /var/lib/jenkins/workspace/Purdue_IGP_2/deployment.yaml
