---
- name: Build, Push, and Deploy Docker Container
  hosts: localhost

  vars:
    dockerhub_username: "{{ dockerhub_username }}"
    dockerhub_password: "{{ dockerhub_password }}"

  tasks:
    - name: Stop and remove existing container
      command: docker rm -f abc_tech:{{ build_number | int - 1 }}
      ignore_errors: true

    - name: Copy WAR file to Docker build context
      copy:
        src: /var/lib/jenkins/workspace/{{ job_name }}/target/ABCtechnologies-1.0.war
        dest: /var/lib/jenkins/workspace/Purdue_IGP/abc_tech.war

    - name: Build Docker image
      command: docker build -t abc_tech:{{ build_number }} .
      args:
        chdir: /var/lib/jenkins/workspace/Purdue_IGP

    - name: Tag Docker image
      command: docker tag abc_tech:{{ build_number }} kowshikreddy137/abc_tech:{{ build_number }}

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        registry_url: "https://index.docker.io/v1/"
      register: login_result

    - name: Debug login result
      debug:
        var: login_result

    - name: Push Docker image to Docker Hub
      command: docker push kowshikreddy137/abc_tech:{{ build_number }}

    - name: Run Docker container
      command: docker run -d --name ABC_Tech_{{ build_number }} -p 8081:8080 kowshikreddy137/abc_tech:{{ build_number }}
