---
- name: Build, Push, and Deploy Docker Container
  hosts: localhost
  tasks:
    - name: Copy WAR file to Docker build context
      copy:
        src: /var/lib/jenkins/workspace/{{ job_name }}/target/ABCtechnologies-1.0.war
        dest: /var/lib/jenkins/workspace/Purdue_IGP/abc_tech.war

    - name: Build Docker image
      command: docker build -t abc_tech:{{ build_number }} .
      args:
        chdir: /var/lib/jenkins/workspace/Purdue_IGP

    - name: Tag Docker image
      command: docker tag abc_tech:{{ build_number }} kowshikreddy137/abc_tech:{{ build_number }}

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker image to Docker Hub
      command: docker push kowshikreddy137/abc_tech:{{ build_number }}

    - name: Run Docker container
      command: docker run -d --name ABC_Tech -p 8080:8080 kowshikreddy137/abc_tech:{{ build_number }}
